#define TK_EOL                           1
#define RW_WHILE                         2
#define TK_LEFT_PAR                      3
#define TK_RIGHT_PAR                     4
#define RW_IF                            5
#define RW_ELSE                          6
#define TK_LEFT_CB                       7
#define TK_RIGHT_CB                      8
#define OP_GT                            9
#define OP_LT                           10
#define OP_GT_EQUAL                     11
#define OP_LT_EQUAL                     12
#define OP_NOT_EQUAL                    13
#define OP_EQUAL                        14
#define TK_VAR                          15
#define OP_ASSIGN                       16
#define RW_PRINT                        17
#define TK_COMMA                        18
#define RW_BIN                          19
#define RW_DEC                          20
#define RW_HEX                          21
#define OP_ADD                          22
#define OP_SUB                          23
#define OP_MUL                          24
#define OP_DIV                          25
#define TK_NUMBER                       26
