#define TK_EOL                           1
#define RW_IF                            2
#define TK_LEFT_PAR                      3
#define TK_RIGHT_PAR                     4
#define RW_ELSE                          5
#define TK_LEFT_CB                       6
#define TK_RIGHT_CB                      7
#define OP_GT                            8
#define OP_LT                            9
#define OP_GT_EQUAL                     10
#define OP_LT_EQUAL                     11
#define OP_NOT_EQUAL                    12
#define OP_EQUAL                        13
#define TK_VAR                          14
#define OP_ASSIGN                       15
#define RW_PRINT                        16
#define TK_COMMA                        17
#define RW_BIN                          18
#define RW_DEC                          19
#define RW_HEX                          20
#define OP_ADD                          21
#define OP_SUB                          22
#define OP_MUL                          23
#define OP_DIV                          24
#define TK_NUMBER                       25
